### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by tomhooijenga** [tomhooijenga/access#2]
Create TypeScript typings and add them to the package.json to support more developers.

**Comment by DmitriiKholodov** [comment]
Hello there, I wanna get the issue, can I?

**Comment by tomhooijenga** [comment]
Sure, go ahead!

**Comment by tomhooijenga** [comment]
Added in https://github.com/tomhooijenga/access/commit/64df862a79eba4d64ec8c10dd4aa8c209dd7a5fa
