### ISSUE TITLE
Update typescript definitions

### ISSUE THREAD

**Issue by tomhooijenga** [tomhooijenga/access#6]
The typescript definition is not up to date with the actual code. For example, the `size` method is missing.

**Comment by MohsinNajmuddin** [comment]
@tomhooijenga can you please elaborate more, like the size method is missing in access file?

**Comment by tomhooijenga** [comment]
You should compare the code and the definitions file. If it doesn't match, update the definitions.

**Comment by tomhooijenga** [comment]
Fixed in 52e923bc1e8da2fab2671113c34e7f0dbdc2ab40
